spring:
  application:
    name: data-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
common:
  cache:
    redis:
      time-to-live: 1800s  # 30分钟
    name: eureka-server