spring:
  application:
    name: trend-trading-backtest-view
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
#  cloud:
#    config: # 如果显性配置spring.cloud.name，则不会读取配置中心默认的配置文件
#      discovery:
#        service-id: config-server
#        enabled: true
#      profile: dev
#      name: trend-trading-backtest-view
#      label: master
# 配置中心客户端使用actuator时
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
