spring:
  application:
    name: trend-trading-backtest-view
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672 # 5672 是 rabbitMQ 服务器的端口， 15672 是 rabbitMQ 自带的某个web工具的端口
    username: guest
    password: guest
#  cloud:
#    config: # 如果显性配置spring.cloud.name，则不会读取配置中心默认的配置文件
#      discovery:
#        service-id: config-server
#        enabled: true
#      profile: dev
#      name: trend-trading-backtest-view
#      label: master
# 配置中心客户端使用actuator时
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
