spring:
  application:
    name: quant-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8051
common:
  cache:
    redis:
      time-to-live: 1800s  # 30分钟
feign.hystrix.enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:5000