spring:
  application:
    name: common-user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quantdatabase?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/