eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: index-zuul-service
zuul:
  prefix: /api
  routes:
    index-service:
      path: /index/**
      serviceId: INDEX-SERVICE
    quant-back-test-service:
      path: /backtest/**
      serviceId: QUANT-BACKTEST-SERVICE
    common-api:
      path: /common/**
      service-id: COMMON-API
