eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: index-zuul-service
zuul:
  prefix: /api
  routes:
    index-codes:
      path: /index-codes/**
      serviceId: INDEX-CODES-SERVICE
    back-test-service:
      path: /backtest/**
      serviceId: TREND-TRADING-BACKTEST-SERVICE
    back-test-view:
      path: /backtest-view/**
      serviceId: TREND-TRADING-BACKTEST-VIEW
