eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: index-zuul-service
zuul:
  prefix: /api
  routes: # 微服务启动时会把主机端口注册到Eureka Server，名称为大写；Zuul基于名称去找对应地址做转发
    data-service:
      path: /data/**
      serviceId: DATA-SERVICE
    quant-service:
      path: /quant/**
      serviceId: QUANT-SERVICE
    common-api:
      path: /common/**
      service-id: COMMON-API
