spring:
  application:
    name: common-api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quantdatabase?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 加上该配置，mybatis自动将下划线转驼峰，否则会拿到null
  type-handlers-package: com.juemuel.trend.handler
  mapper-locations: classpath:mappers/*
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.juemuel.trend.dao.GroupItemMapper: debug