spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juemuel/server-config.git
          default-label: main
          search-paths: java
          skip-ssl-validation: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
